require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-sorbet

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - '*.gemspec'
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Naming/FileName:
  Exclude:
    - 'lib/typed-config.rb'
Style/Documentation:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
