# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Rails; end
module ::Rails::Railtie; end
module TypedConfig::Setup::TypeCoerce; end
module TypedConfig::Structs::Settings; end
